# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'app.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGroupBox,
    QLCDNumber, QLabel, QMainWindow, QPushButton,
    QSizePolicy, QTabWidget, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.logo_frame = QFrame(self.centralwidget)
        self.logo_frame.setObjectName(u"logo_frame")
        self.logo_frame.setGeometry(QRect(10, 10, 1000, 180))
        self.logo_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.logo_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.central_frame = QFrame(self.centralwidget)
        self.central_frame.setObjectName(u"central_frame")
        self.central_frame.setGeometry(QRect(10, 200, 800, 500))
        self.central_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.central_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.tabWidget = QTabWidget(self.central_frame)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(15, 15, 770, 470))
        font = QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.jog_tab = QWidget()
        self.jog_tab.setObjectName(u"jog_tab")
        self.jog_frame = QFrame(self.jog_tab)
        self.jog_frame.setObjectName(u"jog_frame")
        self.jog_frame.setGeometry(QRect(-1, -1, 766, 450))
        self.jog_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.jog_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.groupBox_2 = QGroupBox(self.jog_frame)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(135, 115, 620, 315))
        self.zaxis_groupbox = QGroupBox(self.groupBox_2)
        self.zaxis_groupbox.setObjectName(u"zaxis_groupbox")
        self.zaxis_groupbox.setGeometry(QRect(270, 20, 100, 280))
        self.zplus_btn = QPushButton(self.zaxis_groupbox)
        self.zplus_btn.setObjectName(u"zplus_btn")
        self.zplus_btn.setGeometry(QRect(10, 20, 80, 60))
        self.zplus_btn.setFont(font)
        self.zplus_btn.setAutoFillBackground(False)
        self.zplus_btn.setAutoDefault(False)
        self.zcenter_btn = QPushButton(self.zaxis_groupbox)
        self.zcenter_btn.setObjectName(u"zcenter_btn")
        self.zcenter_btn.setGeometry(QRect(10, 110, 80, 60))
        self.zcenter_btn.setFont(font)
        self.zcenter_btn.setAutoFillBackground(False)
        self.zcenter_btn.setAutoDefault(False)
        self.zminus_btn = QPushButton(self.zaxis_groupbox)
        self.zminus_btn.setObjectName(u"zminus_btn")
        self.zminus_btn.setGeometry(QRect(10, 210, 80, 60))
        self.zminus_btn.setFont(font)
        self.zminus_btn.setAutoFillBackground(False)
        self.zminus_btn.setAutoDefault(False)
        self.extruder_groupbox = QGroupBox(self.groupBox_2)
        self.extruder_groupbox.setObjectName(u"extruder_groupbox")
        self.extruder_groupbox.setGeometry(QRect(385, 20, 100, 280))
        self.eplus_btn = QPushButton(self.extruder_groupbox)
        self.eplus_btn.setObjectName(u"eplus_btn")
        self.eplus_btn.setGeometry(QRect(10, 20, 80, 60))
        self.eplus_btn.setFont(font)
        self.eplus_btn.setAutoFillBackground(False)
        self.eplus_btn.setAutoDefault(False)
        self.ezero_btn = QPushButton(self.extruder_groupbox)
        self.ezero_btn.setObjectName(u"ezero_btn")
        self.ezero_btn.setGeometry(QRect(10, 110, 80, 60))
        self.ezero_btn.setFont(font)
        self.ezero_btn.setAutoFillBackground(False)
        self.ezero_btn.setAutoDefault(False)
        self.eminus_btn = QPushButton(self.extruder_groupbox)
        self.eminus_btn.setObjectName(u"eminus_btn")
        self.eminus_btn.setGeometry(QRect(10, 210, 80, 60))
        self.eminus_btn.setFont(font)
        self.eminus_btn.setAutoFillBackground(False)
        self.eminus_btn.setAutoDefault(False)
        self.steps_groupbox = QGroupBox(self.groupBox_2)
        self.steps_groupbox.setObjectName(u"steps_groupbox")
        self.steps_groupbox.setGeometry(QRect(500, 20, 100, 280))
        self.step1_btn = QPushButton(self.steps_groupbox)
        self.step1_btn.setObjectName(u"step1_btn")
        self.step1_btn.setGeometry(QRect(10, 20, 80, 50))
        self.step1_btn.setFont(font)
        self.step1_btn.setAutoFillBackground(False)
        self.step1_btn.setAutoDefault(False)
        self.step2_btn = QPushButton(self.steps_groupbox)
        self.step2_btn.setObjectName(u"step2_btn")
        self.step2_btn.setGeometry(QRect(10, 85, 80, 50))
        self.step2_btn.setFont(font)
        self.step2_btn.setAutoFillBackground(False)
        self.step2_btn.setAutoDefault(False)
        self.step3_btn = QPushButton(self.steps_groupbox)
        self.step3_btn.setObjectName(u"step3_btn")
        self.step3_btn.setGeometry(QRect(10, 155, 80, 50))
        self.step3_btn.setFont(font)
        self.step3_btn.setAutoFillBackground(False)
        self.step3_btn.setAutoDefault(False)
        self.step4_btn = QPushButton(self.steps_groupbox)
        self.step4_btn.setObjectName(u"step4_btn")
        self.step4_btn.setGeometry(QRect(10, 220, 80, 50))
        self.step4_btn.setFont(font)
        self.step4_btn.setAutoFillBackground(False)
        self.step4_btn.setAutoDefault(False)
        self.groupBox_7 = QGroupBox(self.groupBox_2)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(15, 20, 240, 280))
        self.yplus_btn = QPushButton(self.groupBox_7)
        self.yplus_btn.setObjectName(u"yplus_btn")
        self.yplus_btn.setGeometry(QRect(90, 40, 60, 60))
        self.yplus_btn.setFont(font)
        self.yplus_btn.setAutoFillBackground(False)
        self.yplus_btn.setAutoDefault(False)
        self.xminus_btn = QPushButton(self.groupBox_7)
        self.xminus_btn.setObjectName(u"xminus_btn")
        self.xminus_btn.setGeometry(QRect(10, 110, 60, 60))
        self.xminus_btn.setFont(font)
        self.xminus_btn.setAutoFillBackground(False)
        self.xminus_btn.setAutoDefault(False)
        self.yminus_btn = QPushButton(self.groupBox_7)
        self.yminus_btn.setObjectName(u"yminus_btn")
        self.yminus_btn.setGeometry(QRect(90, 180, 60, 60))
        self.yminus_btn.setFont(font)
        self.yminus_btn.setAutoFillBackground(False)
        self.yminus_btn.setAutoDefault(False)
        self.xplus_btn = QPushButton(self.groupBox_7)
        self.xplus_btn.setObjectName(u"xplus_btn")
        self.xplus_btn.setGeometry(QRect(170, 110, 60, 60))
        self.xplus_btn.setFont(font)
        self.xplus_btn.setAutoFillBackground(False)
        self.xplus_btn.setAutoDefault(False)
        self.home_groupbox = QGroupBox(self.jog_frame)
        self.home_groupbox.setObjectName(u"home_groupbox")
        self.home_groupbox.setGeometry(QRect(10, 115, 110, 315))
        self.xhome_btn = QPushButton(self.home_groupbox)
        self.xhome_btn.setObjectName(u"xhome_btn")
        self.xhome_btn.setGeometry(QRect(15, 20, 80, 60))
        self.xhome_btn.setFont(font)
        self.xhome_btn.setAutoFillBackground(False)
        self.xhome_btn.setAutoDefault(False)
        self.yhome_btn = QPushButton(self.home_groupbox)
        self.yhome_btn.setObjectName(u"yhome_btn")
        self.yhome_btn.setGeometry(QRect(15, 90, 80, 60))
        self.yhome_btn.setFont(font)
        self.yhome_btn.setAutoFillBackground(False)
        self.yhome_btn.setAutoDefault(False)
        self.zhome_btn = QPushButton(self.home_groupbox)
        self.zhome_btn.setObjectName(u"zhome_btn")
        self.zhome_btn.setGeometry(QRect(15, 165, 80, 60))
        self.zhome_btn.setFont(font)
        self.zhome_btn.setAutoFillBackground(False)
        self.zhome_btn.setAutoDefault(False)
        self.home_btn = QPushButton(self.home_groupbox)
        self.home_btn.setObjectName(u"home_btn")
        self.home_btn.setGeometry(QRect(15, 240, 80, 60))
        self.home_btn.setFont(font)
        self.home_btn.setAutoFillBackground(False)
        self.home_btn.setAutoDefault(False)
        self.axiscord_groupbox = QGroupBox(self.jog_frame)
        self.axiscord_groupbox.setObjectName(u"axiscord_groupbox")
        self.axiscord_groupbox.setGeometry(QRect(10, 10, 745, 100))
        self.ecord = QLCDNumber(self.axiscord_groupbox)
        self.ecord.setObjectName(u"ecord")
        self.ecord.setGeometry(QRect(585, 40, 150, 50))
        self.xcord = QLCDNumber(self.axiscord_groupbox)
        self.xcord.setObjectName(u"xcord")
        self.xcord.setGeometry(QRect(10, 40, 150, 50))
        self.ycord = QLCDNumber(self.axiscord_groupbox)
        self.ycord.setObjectName(u"ycord")
        self.ycord.setGeometry(QRect(200, 40, 150, 50))
        self.zcord = QLCDNumber(self.axiscord_groupbox)
        self.zcord.setObjectName(u"zcord")
        self.zcord.setGeometry(QRect(390, 40, 150, 50))
        self.tabWidget.addTab(self.jog_tab, "")
        self.print_tab = QWidget()
        self.print_tab.setObjectName(u"print_tab")
        self.print_frame = QFrame(self.print_tab)
        self.print_frame.setObjectName(u"print_frame")
        self.print_frame.setGeometry(QRect(-1, -1, 766, 450))
        self.print_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.print_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.tabWidget.addTab(self.print_tab, "")
        self.terminal_tab = QWidget()
        self.terminal_tab.setObjectName(u"terminal_tab")
        self.terminal_frame = QFrame(self.terminal_tab)
        self.terminal_frame.setObjectName(u"terminal_frame")
        self.terminal_frame.setGeometry(QRect(-1, -1, 766, 450))
        self.terminal_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.terminal_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.tabWidget.addTab(self.terminal_tab, "")
        self.option_frame = QFrame(self.centralwidget)
        self.option_frame.setObjectName(u"option_frame")
        self.option_frame.setGeometry(QRect(820, 200, 190, 500))
        self.option_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.option_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.machine_box = QGroupBox(self.option_frame)
        self.machine_box.setObjectName(u"machine_box")
        self.machine_box.setGeometry(QRect(10, 210, 170, 280))
        self.machine_box.setFont(font)
        self.xmax_label = QLabel(self.machine_box)
        self.xmax_label.setObjectName(u"xmax_label")
        self.xmax_label.setGeometry(QRect(10, 30, 50, 20))
        self.xmax_label.setFont(font)
        self.ymax_label = QLabel(self.machine_box)
        self.ymax_label.setObjectName(u"ymax_label")
        self.ymax_label.setGeometry(QRect(10, 70, 50, 20))
        self.ymax_label.setFont(font)
        self.zmax_label = QLabel(self.machine_box)
        self.zmax_label.setObjectName(u"zmax_label")
        self.zmax_label.setGeometry(QRect(10, 110, 50, 20))
        self.zmax_label.setFont(font)
        self.esteps_label = QLabel(self.machine_box)
        self.esteps_label.setObjectName(u"esteps_label")
        self.esteps_label.setGeometry(QRect(10, 150, 50, 20))
        self.esteps_label.setFont(font)
        self.textEdit = QTextEdit(self.machine_box)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(70, 25, 80, 30))
        self.textEdit_2 = QTextEdit(self.machine_box)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(70, 65, 80, 30))
        self.textEdit_3 = QTextEdit(self.machine_box)
        self.textEdit_3.setObjectName(u"textEdit_3")
        self.textEdit_3.setGeometry(QRect(70, 105, 80, 30))
        self.textEdit_4 = QTextEdit(self.machine_box)
        self.textEdit_4.setObjectName(u"textEdit_4")
        self.textEdit_4.setGeometry(QRect(70, 145, 80, 30))
        self.set_btn = QPushButton(self.machine_box)
        self.set_btn.setObjectName(u"set_btn")
        self.set_btn.setGeometry(QRect(10, 185, 150, 40))
        self.set_btn.setFont(font)
        self.set_btn.setAutoFillBackground(False)
        self.set_btn.setAutoDefault(False)
        self.factory_btn = QPushButton(self.machine_box)
        self.factory_btn.setObjectName(u"factory_btn")
        self.factory_btn.setGeometry(QRect(10, 230, 150, 40))
        self.factory_btn.setFont(font)
        self.factory_btn.setAutoFillBackground(False)
        self.factory_btn.setAutoDefault(False)
        self.com_box = QGroupBox(self.option_frame)
        self.com_box.setObjectName(u"com_box")
        self.com_box.setGeometry(QRect(10, 10, 170, 180))
        self.com_box.setFont(font)
        self.port_combo = QComboBox(self.com_box)
        self.port_combo.setObjectName(u"port_combo")
        self.port_combo.setGeometry(QRect(70, 20, 90, 30))
        self.port_combo.setFont(font)
        self.baud_combo = QComboBox(self.com_box)
        self.baud_combo.setObjectName(u"baud_combo")
        self.baud_combo.setGeometry(QRect(70, 60, 90, 30))
        self.baud_combo.setFont(font)
        self.port_label = QLabel(self.com_box)
        self.port_label.setObjectName(u"port_label")
        self.port_label.setGeometry(QRect(10, 25, 55, 20))
        self.port_label.setFont(font)
        self.baudrate_label = QLabel(self.com_box)
        self.baudrate_label.setObjectName(u"baudrate_label")
        self.baudrate_label.setGeometry(QRect(10, 65, 55, 20))
        self.baudrate_label.setFont(font)
        self.connect_btn = QPushButton(self.com_box)
        self.connect_btn.setObjectName(u"connect_btn")
        self.connect_btn.setGeometry(QRect(10, 140, 150, 30))
        self.connect_btn.setFont(font)
        self.refresh_btn = QPushButton(self.com_box)
        self.refresh_btn.setObjectName(u"refresh_btn")
        self.refresh_btn.setGeometry(QRect(10, 100, 150, 30))
        self.refresh_btn.setFont(font)
        self.refresh_btn.setAutoFillBackground(False)
        self.refresh_btn.setAutoDefault(False)
        self.status_frame = QFrame(self.centralwidget)
        self.status_frame.setObjectName(u"status_frame")
        self.status_frame.setGeometry(QRect(10, 710, 1000, 50))
        self.status_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.status_frame.setFrameShadow(QFrame.Shadow.Raised)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"JOG Controls", None))
        self.zaxis_groupbox.setTitle(QCoreApplication.translate("MainWindow", u"Z Axis", None))
        self.zplus_btn.setText(QCoreApplication.translate("MainWindow", u"Z +", None))
        self.zcenter_btn.setText(QCoreApplication.translate("MainWindow", u"Z Center", None))
        self.zminus_btn.setText(QCoreApplication.translate("MainWindow", u"Z -", None))
        self.extruder_groupbox.setTitle(QCoreApplication.translate("MainWindow", u"Extruder", None))
        self.eplus_btn.setText(QCoreApplication.translate("MainWindow", u"E +", None))
        self.ezero_btn.setText(QCoreApplication.translate("MainWindow", u"E0", None))
        self.eminus_btn.setText(QCoreApplication.translate("MainWindow", u"E -", None))
        self.steps_groupbox.setTitle(QCoreApplication.translate("MainWindow", u"STEPS", None))
        self.step1_btn.setText(QCoreApplication.translate("MainWindow", u"10 mm", None))
        self.step2_btn.setText(QCoreApplication.translate("MainWindow", u"5 mm", None))
        self.step3_btn.setText(QCoreApplication.translate("MainWindow", u"1 mm", None))
        self.step4_btn.setText(QCoreApplication.translate("MainWindow", u"0.1 mm", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"XY Axis", None))
        self.yplus_btn.setText(QCoreApplication.translate("MainWindow", u"Y +", None))
        self.xminus_btn.setText(QCoreApplication.translate("MainWindow", u"X -", None))
        self.yminus_btn.setText(QCoreApplication.translate("MainWindow", u"Y -", None))
        self.xplus_btn.setText(QCoreApplication.translate("MainWindow", u"X +", None))
        self.home_groupbox.setTitle(QCoreApplication.translate("MainWindow", u"Home", None))
        self.xhome_btn.setText(QCoreApplication.translate("MainWindow", u"X Home", None))
        self.yhome_btn.setText(QCoreApplication.translate("MainWindow", u"Y Home", None))
        self.zhome_btn.setText(QCoreApplication.translate("MainWindow", u"Z Home", None))
        self.home_btn.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.axiscord_groupbox.setTitle(QCoreApplication.translate("MainWindow", u"Axis Displacement", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jog_tab), QCoreApplication.translate("MainWindow", u"JOG", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.print_tab), QCoreApplication.translate("MainWindow", u"PRINT", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.terminal_tab), QCoreApplication.translate("MainWindow", u"TERMINAL", None))
        self.machine_box.setTitle(QCoreApplication.translate("MainWindow", u"Machine Setting", None))
        self.xmax_label.setText(QCoreApplication.translate("MainWindow", u"X Max", None))
        self.ymax_label.setText(QCoreApplication.translate("MainWindow", u"Y Max", None))
        self.zmax_label.setText(QCoreApplication.translate("MainWindow", u"Z Max", None))
        self.esteps_label.setText(QCoreApplication.translate("MainWindow", u"E steps", None))
        self.set_btn.setText(QCoreApplication.translate("MainWindow", u"SET", None))
        self.factory_btn.setText(QCoreApplication.translate("MainWindow", u"FACTORY SETTING", None))
        self.com_box.setTitle(QCoreApplication.translate("MainWindow", u"COM Setting", None))
        self.port_label.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.baudrate_label.setText(QCoreApplication.translate("MainWindow", u"Baudrate", None))
        self.connect_btn.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.refresh_btn.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
    # retranslateUi

